### ISSUE TITLE
Issue with CUDA Runtime Version Compatibility in UAMMD

### ISSUE THREAD

**Issue by eapatinon** [RaulPPelaez/UAMMD#28]
**Description:**
As a beginner in UAMMD implementation, I encountered an issue while trying to run examples and execute tests. Following the recommendation to use Mamba for environment setup with environment.yml and using MKL, I managed to generate binary executables for both examples and test cases using CMake and make. However, during the compilation of binaries for any example case, I encountered a problem related to the CUDA runtime version:

----------------------------------------------------------------------------------------
[ERROR][System] Exception raised at CUDA initialization
terminate called after throwing an instance of 'uammd::cuda_generic_error'
  what():  CudaSafeCall() failed at /home/sph-ed/UAMMD-2.x/examples/../src/System/System.h:106: CUDA driver version is insufficient for CUDA runtime version - code: 35
----------------------------------------------------------------------------------------

**Environment Configuration:**
In my environment, I have the NVIDIA CUDA compiler driver with the following configuration:

-----------------------------------------------------------------------------------------
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
--------------------------------------------------------------------------------------------

Furthermore, when I execute test cases (with make test), the following results are observed:

--------------------------------------------------------------------------------------------
11% tests passed, 42 tests failed out of 47
---------------------------------------------------------------------------------------------

**Question:**
My concern is whether the driver version is incompatible with CUDA runtime, causing these issues. I would appreciate any advice or insights on resolving this problem.

Thank you for your assistance.

![image](https://github.com/RaulPPelaez/UAMMD/assets/61316961/ff70585c-89b3-4a9b-a8ef-20ad82b143e7)

![test](https://github.com/RaulPPelaez/UAMMD/assets/61316961/307767dd-0978-4fbb-b08e-7461c63e5b1a)

**Comment by RaulPPelaez** [comment]
Hi! You got the latest CUDA version from mamba, 12.3. But your driver version is too old for it. 
You can check the driver version with nvidia-smi. You have more information about driver compatibility here:
https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility

Depending on the GPU you have available it might be possible that CUDA 12.3 is too new for it (I believe CUDA 12 deprecated architectures prior to sm_50). There is more information about architectures and CUDA versions here: https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

You may downgrade your cuda version using mamba, but the procedure is different depending on wether you need CUDA >12 or otherwise. You have more information here https://github.com/conda-forge/conda-forge.github.io/issues/1963
