### ISSUE TITLE
BDHI::PSE can' work normally

### ISSUE THREAD

**Issue by biubiuubiuu** [RaulPPelaez/UAMMD#38]
After successfully reading the particle coordinates and topology file, BDHI::PSE appears to stop computing and produces no calculation output.  I have defined the integrator in the JSON file and included bond, angle, DLVO, and electrostatics in the forcefield. How can I troubleshoot this issue?
[simulation.json](https://github.com/user-attachments/files/17699540/simulation.json)

> [MESSAGE] [ExtendedSystem] (system) Name: ROD
> [MESSAGE] [ExtendedSystem] (system) Seed: 1731312105444491820
> [WARNING] [Time] No timeStep specified, using 0.0 as default.
> [MESSAGE] [Basic] Loaded type A1, mass: 11930.549805, radius: 1.569230, charge: -4.759999
> [MESSAGE] [Basic] Loaded type A2, mass: 11313.146484, radius: 1.601480, charge: -1.279999
> [MESSAGE] [Basic] Loaded type A3, mass: 13708.338867, radius: 1.479150, charge: 2.095001
> [MESSAGE] [Basic] Loaded type A4, mass: 11965.326172, radius: 1.694730, charge: 1.410001
> [MESSAGE] [Basic] Loaded type A5, mass: 12811.560547, radius: 1.334270, charge: 2.310001
> [MESSAGE] [Basic] Loaded type A6, mass: 14176.355469, radius: 1.380070, charge: 5.755001
> [MESSAGE] [Basic] Loaded type A7, mass: 10825.169922, radius: 1.706570, charge: 2.220001
> [MESSAGE] [Basic] Loaded type A8, mass: 12993.669922, radius: 1.325760, charge: 2.480001
> [MESSAGE] [Basic] Loaded type A9, mass: 12427.835938, radius: 1.276650, charge: -1.224999
> [MESSAGE] [Basic] Loaded type A10, mass: 16827.960938, radius: 1.701190, charge: 3.050001
> [MESSAGE] [Basic] Loaded type A11, mass: 11400.957031, radius: 1.557780, charge: 3.295001
> [MESSAGE] [Basic] Loaded type A12, mass: 6589.383301, radius: 1.620060, charge: 0.650001
> [MESSAGE] [ParticleData] Created with 6144 particles.
> [MESSAGE] [StateLoader] Loading property "id".
> [MESSAGE] [StateLoader] Loading property "position".
> [MESSAGE] [Topology] Loading types into particle data.
> [WARNING] [InputEntryManager] (forceField) Entry forceField not found.
> [MESSAGE] [ParticleGroup] Group All created with All selector
> [MESSAGE] [ParticleGroup] Group All contains 6144 particles.
> [MESSAGE] [GroupsListFromInputEntries] Added group "All" with 6144 particles.
> [MESSAGE] [Interactor] Scheduled created.
> [MESSAGE] [Interactor] Acting on group All
> [MESSAGE] [ParticleGroup] Group All created with All selector
> [MESSAGE] [ParticleGroup] Group All contains 6144 particles.
> [MESSAGE] [GroupsListFromInputEntries] Added group "All" with 6144 particles.
> [MESSAGE] [IntegratorManager] (integrator) Integrator 'pse' will run for 100 steps with order 1.
> [MESSAGE] [ParticleGroupFromGroupsList] No group name specified, using "All".
> [MESSAGE] [ParticleGroupFromGroupsList] Using group "All".
> [MESSAGE] [Integrator] pse created.
> [MESSAGE] [Integrator] Acting on group All
> [MESSAGE] [ExtendedSystem] (system) Creating cuda stream
> [MESSAGE] [IntegratorBase] (pse) Time step: 0.002000
> [MESSAGE] [IntegratorBase] (pse) Current step: 0
> [MESSAGE] [IntegratorBaseNVT] (pse) Temperature: 1.000000
> [MESSAGE] [IntegratorBaseNVT] (pse) kBT (kB 1.000000): 1.000000
> [MESSAGE] [BDHI] Viscosity: 1.000000
> [MESSAGE] [BDHI] Hydrodynamic radius: 2.000000
> [MESSAGE] [BDHI] Tolerance: 2.000000
> [MESSAGE] [BDHI] PSI: 0.500000
> [MESSAGE] [Integrator] BDHI::EulerMaruyama/uammd::BDHI::PSE created.
> [MESSAGE] [Integrator] Acting on group All
> [MESSAGE] [BDHI::PSE] Initialized
> [MESSAGE] [BDHI::PSE] Self mobility: 0.026366
> [MESSAGE] [CellList] Created
> [MESSAGE] [BDHI::PSE] Number of real RPY texture points: 16384
> [MESSAGE] [BDHI::PSE] Close range distance cut off: -nan
> [MESSAGE] [BDHI::PSE] Far range wave number cut off: -nan

**Comment by RaulPPelaez** [comment]
This is an issue with the tolerance AFAICT. This parameter controls the overall error threshold for the algorithm. It is a unit-less quantity which should be "small", you can interpret it as -log(tolerance) being roughly the number of significant digits that will be correct in the quantities computed by the algorithm.
Try setting it to 1e-4. The lower the tolerance, the higher the cost of the algorithm.

I added a check for this and clarified it usage in the documentation #39. 
Thanks.

**Comment by RaulPPelaez** [comment]
>  [WARNING] [Simulation] Error running simulation: [Lanczos] Could not diagonalize tridiagonal krylov matrix, steqr failed with code -4 
This usually means PSE has received some kind of impossible situation, for instance forces or positions that are infinity/NaN. Most of the time this points to the simulation blowing up.

Your second inquiry makes me think you are in fact trying to run UAMMD-structure, since there is no InputJSON in UAMMD proper. You should ask in that repo, but perhaps @PabloIbannez can help you here?

**Comment by PabloIbannez** [comment]
Thank you for providing the detailed logs and following up on the tolerance issue. After analyzing the situation and seeing that the Lanczos diagonalization error persists even after removing forces, I believe we need to take a step back and address some fundamental aspects of the simulation setup.

The Lanczos error (steqr failed with code -4) typically indicates that the simulation has encountered numerically impossible situations (like infinities or NaNs). This, combined with the issues we found in the original configuration file, suggests we need a more systematic approach to setting up the simulation.

I've created a script that addresses several key issues in the simulation.json:

```
import json
import copy
import pyUAMMD

with open("simulation.json") as f:
    previous = json.load(f)
sim = pyUAMMD.simulation(simulationJSON=previous)

# Fix tolerance
sim["integrator"]["pse"]["parameters"]["tolerance"] = 1e-1

# Reduce splitting, otherwise an error regarding not enough memory will appear
sim["integrator"]["pse"]["parameters"]["psi"]=0.05

# Remove temperature parameter, on this way the given in ensemble will be used, ensuring consistency
del sim["integrator"]["pse"]["parameters"]["temperature"]

# Change the value of themperature in ensemble to 1.0 (since no units are given, it is assumed to be in reduced units, the previous value 310.0 was too high)
sim["global"]["ensemble"]["data"][0][1] = 1.0

# Change key "forcefield" to "forceField"
sim["topology"]["forceField"] = copy.deepcopy(sim["topology"]["forcefield"])
del sim["topology"]["forcefield"]

# Data in bond2 must be int,int,float,float but it is int,int,str,str
for bond in sim["topology"]["forceField"]["bond2"]["data"]:
    bond[2] = float(bond[2])
    bond[3] = float(bond[3])

# Data in bond3 must be int,int,int,float,float but it is int,int,int,str,str
for bond in sim["topology"]["forceField"]["bond3"]["data"]:
    bond[3] = float(bond[3])
    bond[4] = float(bond[4])

# Add neighbor list, this is necessary since you are using a short range potential
sim["topology"]["forceField"]["nl"] = {
    "type": ["VerletConditionalListSet", "all"],
    "parameters": {"cutOffVerletFactor": 1.2}
}

# Increase the interval a snapshot is saved
sim["simulationStep"]["saveState"]["parameters"]["intervalStep"] = 1000

# DEBUG: remove all interactions
del sim["topology"]["forceField"]

sim.write("simulationFixed.json")
```

However, since the error persists even with no forces, I recommend taking an incremental approach to building your simulation. Start with a minimal working system using only the PSE integrator. In this base setup:

- Use no additional forces initially
- Set temperature to 1.0 (in reduced units)
- Configure PSE with moderate parameters (tolerance = 1e-4, psi = 0.05)

Once this basic system is stable, gradually add components in this sequence:

- First add the neighbor list (crucial for short-range potentials)
- Then add forces one at a time (bonds, angles, etc.)
- Test thoroughly after each addition

The key point to remember is that when no units are specified, the simulation runs in reduced units. This means values like the original temperature of 310.0 were too high for a reduced units system. All parameters should typically be O(1) in reduced units.

Also, since you're using UAMMD-structure, you might want to move future discussions to that repository for more specific help with the structure-related features.

**Comment by RaulPPelaez** [comment]
@biubiuubiuu We found an initialization bug in PSE that might have affected you in #40 , the fix is now merged into master and available in the latest release. @PabloIbannez should include it in UAMMD-structured soon.

**Comment by biubiuubiuu** [comment]
I am wondering whether the PSE+DLVO method is suitable for systems with periodic boundary conditions? When I run simulations in a specified box size with PSE+DLVO method, the molecular structure breaks into multiple particles, even if I have added bond and angle restraint potentials. However, when I appropriately enlarge the simulation box, the molecular structure is preserved, and the simulation proceeds normally.
